# This is the list of users to generate.
# Every device must have a unique username.
users:
  - phone
  - laptop
  - desktop

# TODO: delete ssh authorized keys
# unmanaged: false

# Deploy IPsec (StrongSwan)
# !!! THIS IS NOT YET SUPPORTED
ipsec:
  enabled: false
  log_level: 2
  ipv4: "10.48.0.0/16"
  ipv6: "2001:db8:4160::/48"
  ciphers:
    ike: aes256gcm16-prfsha512-ecp384!
    esp: aes256gcm16-ecp384!

# Deploy WireGuard
wireguard:
  enabled: true
  ipv4: "10.49.0.0/16"
  ipv6: "2001:db8:a160::/48"
  port: 51820

  # If you're behind NAT or a firewall and you want to receive incoming connections long after network traffic has gone silent.
  # This option will keep the "connection" open in the eyes of NAT.
  # See: https://www.wireguard.com/quickstart/#nat-and-firewall-traversal-persistence
  persistent_keepalive: 0

# Reduce the MTU of the VPN tunnel
# Some cloud and internet providers use a smaller MTU (Maximum Transmission
# Unit) than the normal value of 1500 and if you don't reduce the MTU of your
# VPN tunnel some network connections will hang. Algo will attempt to set this
# automatically based on your server, but if connections hang you might need to
# adjust this yourself.
# See: https://github.com/trailofbits/algo/blob/master/docs/troubleshooting.md#various-websites-appear-to-be-offline-through-the-vpn
reduce_mtu: 0

ssh_tunneling:
  enabled: true

dns:
  adblocking:
    enabled: false
    lists:
      - "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
      - "https://hosts-file.net/ad_servers.txt"

  encryption:
    # Enable DNS encryption.
    # If 'false', resolvers should be specified below.
    # Can not be disabled if adblocking is enabled
    enabled: true

    # DNS servers which will be used if dns encryption is enabled. Multiple
    # providers may be specified, but avoid mixing providers that filter results
    # (like Cisco) with those that don't (like Cloudflare) or you could get
    # inconsistent results. The list of available public providers can be found
    # here:
    # https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v2/public-resolvers.md
    servers:
      ipv4:
        - cloudflare
      ipv6:
        - cloudflare-ipv6

  # DNS resolvers which will be used if dns encryption is disabled
  # The default is to use Cloudflare.
  resolvers:
    ipv4:
      - "1.1.1.1"
      - "1.0.0.1"
    ipv6:
      - "2606:4700:4700::1111"
      - "2606:4700:4700::1001"

# Block traffic between connected clients
block_traffic_between_clients: true
block_smb: true

# Your Algo server will automatically install security updates. Some updates
# require a reboot to take effect but your Algo server will not reboot itself
# automatically unless you change 'enabled' below from 'false' to 'true', in
# which case a reboot will take place if necessary at the time specified (as
# HH:MM) in the time zone of your Algo server. The default time zone is UTC.
unattended_reboot:
  enabled: true
  time: "06:00"

clouds:
  digitalocean:
    image: "ubuntu-24-04-x64"
    size: "s-1vcpu-1gb"
    region: "sfo2"
    ipv6: true

  ec2:
    image: "ubuntu-noble-24.04"
    size: "t2.micro"
    region: "us-west-1"
    ipv6: true
    encrypted: true
    kms_key_id: null

  lightsail:
    image: "ubuntu_24_04"
    size: "nano_2_0"
    availability_zone: "us-west-2a"
    ipv6: true

  # az login
  azure:
    offer: "ubuntu-24_04-lts"
    image: "server"
    size: "Standard_B1ls"
    location: "westus"
    ipv6: true
    subscription_id: "00000000-0000-0000-0000-0000000000" # az account list

  # gcloud auth login && gcloud auth application-default login
  gce:
    image: "ubuntu-2404-lts-amd64"
    size: "e2-micro"
    region: "us-west1"
    ipv6: true                # https://cloud.google.com/vpc/docs/vpc#ipv6-regions
    project: "algo-140311"    # gcloud projects list

  # local-server:
  #   # Local installation can break your server, use at your own risk
  #   ip: "3.65.207.122"
  #   user: "ubuntu"
  #   ssh_private_key: "/Users/jack/.ssh/id_ecdsa" # password protected keys are not supported
  #   ipv6: true
