#cloud-config
apt:
  sources:
    shevchuk-ubuntu-dnscrypt-proxy.list:
      source: ppa:shevchuk/dnscrypt-proxy

packages:
 - dnscrypt-proxy

write_files:
  - path: /etc/apparmor.d/usr.bin.dnscrypt-proxy
    permissions: '0644'
    content: ${jsonencode(vars.apparmor_dnscrypt-proxy)}

  - path: /etc/systemd/system/dnscrypt-proxy.service.d/99-capabilities.conf
    permissions: '0644'
    content: |
      [Service]
      AmbientCapabilities=CAP_NET_BIND_SERVICE

  - path: /etc/dnscrypt-proxy/ip-blacklist.txt
    permissions: '0644'
    content: ${jsonencode(vars.ip-blacklist)}

  - path: /etc/dnscrypt-proxy/dnscrypt-proxy.toml
    permissions: '0644'
    content: ${jsonencode(vars.dnscrypt_proxy_toml)}

runcmd:
  - aa-enforce /etc/apparmor.d/usr.bin.dnscrypt-proxy
  - systemctl daemon-reload
  - systemctl restart dnscrypt-proxy
  - systemctl enable dnscrypt-proxy
