server_names      = [ '${join("', '", vars.server_names)}' ]
listen_addresses  = [ '127.0.0.1:53' ]
max_clients = 250
ipv4_servers = true
ipv6_servers = ${vars.ipv6}
dnscrypt_servers = true
doh_servers = true
require_dnssec = true
require_nolog = true
require_nofilter = true
force_tcp = false
timeout = 2500
keepalive = 30
lb_strategy = 'p2'
log_level = 2
use_syslog = true
cert_refresh_delay = 240
dnscrypt_ephemeral_keys = true
tls_disable_session_tickets = true
fallback_resolver = '127.0.0.53:53'
ignore_system_dns = true
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1
block_ipv6 = false
cache = true
cache_size = 512
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600
refused_code_in_responses = false
netprobe_timeout = 60
netprobe_address = "1.1.1.1:53"
[query_log]
  format = 'tsv'
[nx_log]
  format = 'tsv'
[blacklist]
  ${vars.blacklist_file}
[ip_blacklist]
  blacklist_file = 'ip-blacklist.txt'
[whitelist]
[schedules]
[sources]
  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''
[static]
